logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS, UTC
server:
  port: 8080
spring:
  application:
    name: team6
  batch:
    jdbc:
      initialize-schema: "always"
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:mysql://localhost:3306/music?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: password
  session:
    store-type: jdbc
application:
  hostname: http://localhost:8080